# Generated by Django 6.0.1 on 2026-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_url',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
    ]
