# Generated by Django 6.0.1 on 2026-02-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
